# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-08 00:25
from __future__ import unicode_literals

from django.db import migrations
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_auth.models.CustomUserManager()),
            ],
        ),
    ]
